//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace SQLite
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Book>();
            }
        }
    }
    public partial class Book
    {
        [PrimaryKey]
        public Int64 a { get; set; }
        
        [MaxLength(500)]
        [NotNull]
        public String b { get; set; }
        
    }
    
}
